create table new_user
(
  id   integer generated by default as identity (start with 1 increment by 1)  primary key,
  login    varchar(250) not null,
  mail     varchar(250) not null,
  password varchar(250) not null
);


create table new_file
(
  id       integer generated by default as identity (start with 1 increment by 1)  primary key ,
  count_down     integer      not null,
  data      timestamp    not null,
  file      BLOB,
  info      varchar(255) not null,
  name_file varchar(255) not null,
  status    varchar(255) not null,
  type      varchar(255) not null,
  user_id   integer references new_user(id)
);
